local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("statusbar", "Malyxi's Dragonflight Status Bar",
[[Interface\AddOns\MalyxiUI\media\textures\status-bar.tga]])
LSM:Register('statusbar', "RillyClean Status Bar", [[Interface\AddOns\MalyxiUI\media\textures\rc-status-bar.tga]])
LSM:Register('statusbar', "Malyxi's Blizz Inspired Bar", [[Interface\AddOns\MalyxiUI\media\textures\blizz-inspired.tga]])

for name, fontPath in pairs(EUI_FONTS) do
  LSM:Register("font", name, fontPath)
end

LSM:Register("sound", "airforcebase", [[Interface\Addons\MalyxiUI\media\sound\airforcebase.ogg]])
LSM:Register("sound", "garou-specialko", [[Interface\Addons\MalyxiUI\media\sound\garouspecialko.ogg]])
LSM:Register("sound", "garou-fullko", [[Interface\Addons\MalyxiUI\media\sound\garou-fullko.ogg]])
LSM:Register("sound", "garou-kitaa", [[Interface\Addons\MalyxiUI\media\sound\garou-kitaa.ogg]])
LSM:Register("sound", "garou-ko", [[Interface\Addons\MalyxiUI\media\sound\garou-ko.ogg]])
LSM:Register("sound", "GuilesThemeOrig", [[Interface\Addons\MalyxiUI\media\sound\GuilesThemeOrig.ogg]])
LSM:Register("sound", "guilesthemeproc", [[Interface\Addons\MalyxiUI\media\sound\guilesthemeproc.ogg]])
LSM:Register("sound", "guilesthemesnes", [[Interface\Addons\MalyxiUI\media\sound\guilesthemesnes.ogg]])
LSM:Register("sound", "guilsethemecps2ext", [[Interface\Addons\MalyxiUI\media\sound\guilsethemecps2ext.ogg]])
LSM:Register("sound", "kentheme+10", [[Interface\Addons\MalyxiUI\media\sound\kentheme+10.ogg]])
LSM:Register("sound", "kentheme+5-20s", [[Interface\Addons\MalyxiUI\media\sound\kentheme+5-20s.ogg]])
LSM:Register("sound", "kentheme+5", [[Interface\Addons\MalyxiUI\media\sound\kentheme+5.ogg]])
LSM:Register("sound", "kentheme+8", [[Interface\Addons\MalyxiUI\media\sound\kentheme+8.ogg]])
LSM:Register("sound", "kentheme", [[Interface\Addons\MalyxiUI\media\sound\kentheme.ogg]])
LSM:Register("sound", "kentheme30s+10", [[Interface\Addons\MalyxiUI\media\sound\kentheme30s+10.ogg]])
LSM:Register("sound", "kenthemebuildup+5", [[Interface\Addons\MalyxiUI\media\sound\kenthemebuildup+5.ogg]])
LSM:Register("sound", "kenthemebuildup-.5+10db", [[Interface\Addons\MalyxiUI\media\sound\kenthemebuildup-.5+10db.ogg]])
LSM:Register("sound", "kenthemebuildup-.5", [[Interface\Addons\MalyxiUI\media\sound\kenthemebuildup-.5.ogg]])
LSM:Register("sound", "kenthemebuildup-.5s+5db", [[Interface\Addons\MalyxiUI\media\sound\kenthemebuildup-.5s+5db.ogg]])
LSM:Register("sound", "kenthemebuildup", [[Interface\Addons\MalyxiUI\media\sound\kenthemebuildup.ogg]])
LSM:Register("sound", "mario-invincibility-2secfade+10db", [[Interface\Addons\MalyxiUI\media\sound\mario-invincibility-2secfade+10db.ogg]])
LSM:Register("sound", "mario-invincibility-2secfade", [[Interface\Addons\MalyxiUI\media\sound\mario-invincibility-2secfade.ogg]])
LSM:Register("sound", "MinorCircuit", [[Interface\Addons\MalyxiUI\media\sound\minorcircuit.ogg]])
LSM:Register("sound", "JohnCena", [[Interface\Addons\MalyxiUI\media\sound\johncena.ogg]])
